pipe on validate tag

diff --git a/.github/workflows/on-tag.yaml b/.github/workflows/on-tag.yaml
--- a/.github/workflows/on-tag.yaml
+++ b/.github/workflows/on-tag.yaml
@@ -8,6 +8,14 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
+      - name: Validate tag format
+        run: |
+          if [[ ! $GITHUB_REF =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "Tag format is invalid. Expected format: vX.Y.Z"
+            exit 1
+          fi
+    steps:
+      - uses: actions/checkout@v2
       - name: Run a one-line script
         run: echo "Hola Mundo, desde un tag"
 
